# Site settings
title: Gungnir
SEOTitle: Jekyll theme Gungnir
description: Jekyll version of the blog theme Gungnir.
keyword: "jekyll, theme, blog, blog theme"
url: "https://spidychoi.github.io"
baseurl: "/sori-cafe"
avatar: "img/header-avatar.jpeg"

# GitHub repository (if the site is hosted by GitHub)
repository: spidychoi/sori-cafe
repository_branch: main

# Theme style settings
theme_style:
  highlight:    # "dark" (default), "light"
  alert:        # "flat" (default), "modern"
  post_preview: # "image" (default), "text"

# Markdown enhancements settings
math:
  enable: true
  engine:         # "katex" (default), "mathjax"
chart: true
mermaid: true
emoji-plus: true

# CDN settings
cdn:
  source:       # "jsdelivr" (default), "bootcdn", "unpkg", "cdnjs"
  enable:       # false (default), true

future: true

collections:
  experiences:
    output: true
  publications:
    output: true
  projects:
    output: true

# SNS settings
sns:
  RSS: true
  github_username: spidychoi
  weibo_username:
  zhihu_username:
  twitter_username:
  facebook_username:
  linkedin_username:
  email_address:

# Build settings
permalink: pretty
paginate: 10
exclude:
  - package.json
  - package-lock.json
  - README.md
  - README-CN.md
  - LICENSE
  - Gruntfile.js
  - Gemfile
  - Gemfile.lock
  - /node_modules
anchorjs: true

# Gems
plugins:
  - jekyll-paginate
  - jemoji

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

# Navigation menu settings
menus:
  - title: Home
    font: fab fa-fort-awesome
    url: /
  - title: About
    font: fas fa-paw
    submenus:
      - title: Me
        font: fas fa-user-astronaut
        url: /about/
      - title: Theme
        font: fas fa-meteor
        url: /theme/
  - title: Archive
    font: fas fa-archive
    url: /archive/
  - title: Links
    font: fas fa-link
    url: /links/

# Comment settings
comment:
  provider: gitalk

  # Disqus settings
  disqus_username: spidychoi

  # Gitalk settings
  gitalk:
    clientID: 'YOUR_GITHUB_CLIENT_ID'
    clientSecret: 'YOUR_GITHUB_CLIENT_SECRET'
    repo: 'YOUR_GITHUB_REPOSITORY_FOR_COMMENTS'
    owner: spidychoi
    admin:
      - spidychoi

  # Valine settings
  valine:
    appID:
    appKey:

# Analytics settings
analytics:
  ba_track_id: 00504d7a0bf51278aa92b36e60e830b5
  ga_track_id: 'G-ZYM02DSEHS'

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true
hitokoto: true
